import 'models.dart';

const facilities = <Facility>[
  Facility(
    name: 'Mandeville Regional Hospital',
    type: 'Regional hospital',
    parish: 'Manchester',
    suggested: true,
  ),
  Facility(
    name: 'Junction Health Centre',
    type: 'Health centre',
    parish: 'St. Elizabeth',
  ),
  Facility(
    name: 'Spalding Health Centre',
    type: 'Health centre',
    parish: 'Clarendon',
  ),
];

const demoPatients = <Patient>[
  Patient(
    id: 'PT-10041',
    encounterId: 'ENC-26-0831-041',
    name: 'Alicia Grant',
    age: 32,
    sex: 'Female',
    chiefComplaint: 'Shortness of breath and wheezing',
    triageLevel: TriageLevel.urgent,
    waitMinutes: 7,
    vitals: {
      'BP': '128/82',
      'Pulse': '104 bpm',
      'Temp': '37.2 °C',
      'SpO₂': '94%',
    },
    allergies: ['Penicillin'],
    history: ['Asthma', 'Seasonal allergies'],
    triageNote: 'Speaking in full sentences. Mild expiratory wheeze. No chest pain.',
    nidsVerified: true,
  ),
  Patient(
    id: 'PT-10042',
    encounterId: 'ENC-26-0831-042',
    name: 'Devon Campbell',
    age: 58,
    sex: 'Male',
    chiefComplaint: 'Dizziness and elevated blood pressure',
    triageLevel: TriageLevel.standard,
    waitMinutes: 18,
    vitals: {
      'BP': '168/96',
      'Pulse': '86 bpm',
      'Temp': '36.8 °C',
      'SpO₂': '98%',
    },
    allergies: [],
    history: ['Hypertension'],
    triageNote: 'Alert and oriented. Denies focal weakness or chest pain.',
    nidsVerified: true,
  ),
  Patient(
    id: 'PT-10043',
    encounterId: 'ENC-26-0831-043',
    name: 'Nia Williams',
    age: 10,
    sex: 'Female',
    chiefComplaint: 'Fever and sore throat',
    triageLevel: TriageLevel.low,
    waitMinutes: 29,
    vitals: {
      'BP': '104/66',
      'Pulse': '98 bpm',
      'Temp': '38.1 °C',
      'SpO₂': '99%',
    },
    allergies: [],
    history: ['No chronic conditions recorded'],
    triageNote: 'Tolerating fluids. No breathing difficulty. Parent present.',
    nidsVerified: true,
  ),
  Patient(
    id: 'TEMP-008',
    encounterId: 'ENC-26-0831-044',
    name: 'Unknown Patient 008',
    age: 0,
    sex: 'Unknown',
    chiefComplaint: 'Unidentified patient — assessment in progress',
    triageLevel: TriageLevel.critical,
    waitMinutes: 0,
    vitals: {
      'BP': '—',
      'Pulse': '—',
      'Temp': '—',
      'SpO₂': '—',
    },
    allergies: [],
    history: ['Temporary emergency encounter'],
    triageNote: 'Emergency care may proceed before identity is established.',
    nidsVerified: false,
  ),
];
