/// Controlled prescribing choices used by the doctor prescription workflow.
///
/// Long lists are kept out of the primary screen and opened only when needed.
/// Routes are alphabetical so clinicians can scan the list quickly.
abstract final class MedicationPrescribingOptions {
  static const routes = <String>[
    'Buccal',
    'Enteral / feeding tube',
    'Epidural',
    'Inhaled',
    'Intradermal',
    'Intramuscular (IM)',
    'Intranasal',
    'Intraosseous (IO)',
    'Intrathecal',
    'Intravenous (IV)',
    'Nebulized',
    'Ophthalmic',
    'Oral',
    'Otic',
    'Rectal',
    'Subcutaneous',
    'Sublingual',
    'Topical',
    'Transdermal',
    'Vaginal',
  ];

  /// Controlled duration choices shown as a dropdown. A legacy duration that
  /// was saved before this list existed is preserved by the composer as an
  /// additional selected option rather than being discarded.
  static const durations = <String>[
    'Not specified',
    'Single dose',
    '1 day',
    '2 days',
    '3 days',
    '4 days',
    '5 days',
    '6 days',
    '7 days',
    '8 days',
    '9 days',
    '10 days',
    '11 days',
    '12 days',
    '13 days',
    '14 days',
    '15 days',
    '16 days',
    '17 days',
    '18 days',
    '19 days',
    '20 days',
    '21 days',
    '22 days',
    '23 days',
    '24 days',
    '25 days',
    '26 days',
    '27 days',
    '28 days',
    '29 days',
    '30 days',
    '4 weeks',
    '6 weeks',
    '8 weeks',
    '12 weeks',
    '1 month',
    '2 months',
    '3 months',
    '6 months',
    '12 months',
    'Until course completed',
    'Until reviewed',
    'Ongoing',
  ];

  /// Searchable optional counseling/instruction templates. These are never
  /// auto-applied to a medicine: the prescriber must deliberately select the
  /// instructions that are clinically appropriate for that patient/product.
  /// The library intentionally includes opposite instructions (for example
  /// "take with food" and "take on an empty stomach") because different
  /// medicines require different directions.
  static const commonInstructions = <String>[
    'Allow to dissolve completely before swallowing',
    'Allow to dissolve under the tongue',
    'Apply a thin layer to the affected area',
    'Apply to clean, dry, intact skin',
    'Apply to the affected area',
    'Avoid alcohol',
    'Avoid caffeine while taking this medicine',
    'Avoid coffee around the time of this dose',
    'Avoid direct sunlight or tanning lamps',
    'Avoid grapefruit and grapefruit juice',
    'Avoid herbal remedies or supplements unless approved by the prescriber or pharmacist',
    'Avoid milk and dairy products around the time of this dose',
    'Avoid tea around the time of this dose',
    'Avoid tea and coffee within 2 hours of this dose',
    'Avoid tea, coffee, milk, dairy products and eggs within 2 hours of this dose',
    'Avoid using antacids within 2 hours of this dose',
    'Avoid vitamins or mineral supplements containing calcium, iron, magnesium or zinc within 2 hours of this dose',
    'Chew thoroughly before swallowing',
    'Complete the full course unless the prescriber tells you to stop',
    'Do not chew the capsule',
    'Do not crush, chew or split this medicine',
    'Do not cut the patch',
    'Do not double the next dose if a dose is missed',
    'Do not drive or operate machinery if drowsy, dizzy or vision is affected',
    'Do not exceed the prescribed maximum dose in 24 hours',
    'Do not lie down for at least 30 minutes after taking this medicine',
    'Do not mix with alcohol',
    'Do not stop suddenly unless instructed by the prescriber',
    'Do not swallow the mouth rinse',
    'Do not take at the same time as antacids',
    'Do not take at the same time as calcium, iron, magnesium or zinc supplements',
    'Do not take with dairy products',
    'Do not take with grapefruit or grapefruit juice',
    'Do not take with milk',
    'Do not use on broken or irritated skin unless instructed',
    'Dissolve or disperse in water before taking',
    'For external use only',
    'Insert rectally as directed',
    'Insert vaginally as directed',
    'Instill into the affected ear as directed',
    'Instill into the affected eye as directed',
    'Keep taking this medicine until the prescribed course is completed',
    'Let the tablet dissolve in the mouth; do not chew',
    'May cause dizziness; stand up slowly',
    'May cause drowsiness',
    'May increase sensitivity to sunlight; use sun protection',
    'Measure each liquid dose with an oral syringe, cup or spoon made for medicines',
    'Mix with the amount of water or liquid specified by the prescriber or pharmacist',
    'Place under the tongue and allow to dissolve; do not swallow immediately',
    'Prime the inhaler before use when required by the product instructions',
    'Remove the old patch before applying a new patch',
    'Rinse mouth after each inhaled dose',
    'Rotate patch or application sites',
    'Shake inhaler well before use',
    'Shake well before each dose',
    'Space doses as evenly as possible through the day',
    'Swallow whole',
    'Take 30 minutes before food',
    'Take 1 hour before food',
    'Take 2 hours after food',
    'Take after food',
    'Take at bedtime',
    'Take at the same time each day',
    'Take before food',
    'Take immediately after a meal',
    'Take in the morning',
    'Take on an empty stomach',
    'Take only as needed',
    'Take with a full glass of water',
    'Take with food',
    'Take with food or just after food',
    'Take with milk',
    'Take with orange juice or another vitamin C source when specifically instructed',
    'Take with or without food',
    'Take with plenty of water',
    'Take with water',
    'Use a spacer device with the inhaler if prescribed',
    'Use as directed',
    'Use sunscreen and protective clothing while taking this medicine',
    'Wait at least 2 hours after dairy products before taking this dose',
    'Wash hands before and after applying this medicine',
  ];
}
